# Generated by Django 5.2.3 on 2025-12-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(blank=True, choices=[('Farmer', 'Farmer'), ('Buyer', 'Buyer')], default='Buyer', max_length=10),
        ),
    ]
